version: '3'
services:
  avrist-frontpage-web:
    container_name: avrist-frontpage-web-app
    image: avrist-frontpage-web
    build:
      context: .                          
      dockerfile: Dockerfile  
    ports:
      - "3031:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - avrist-network
networks:
  avrist-network:
    driver: 'bridge'