#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

message="$(cat $1)"
requiredPattern="ACW2-([0-9]+)(\|([0-9]+))?(\|([0-9]+))?(\|([0-9]+))?(\|([0-9]+))?(\|([0-9]+))?(\|([0-9]+))?: ([a-zA-Z0-9\s]+)"
if ! [[ $message =~ $requiredPattern ]];
then
  echo " "
  echo "💻 🤷"
  echo " "
  echo "🚨 Wrong commit message! 😕"
  echo "The commit message must have this format:"
  echo "<id_jira>-<number_card>: <message_commit>"
  echo " "
  echo "Example:"
  echo "ACW2-207: Add validate email & password"
  echo " "
  echo "Your commit message was:"
  echo $message
  echo " "
  echo "For more information, check https://bit.ly/3UnrqjY"
  echo " "
  exit 1
fi

